spring.application.name=kaiburr-task
spring.data.mongodb.uri=mongodb+srv://rdevika861:1234@cluster1.1qoqukt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
spring.data.mongodb.database=kaiburr
server.port=8080
